server:
  port: 2000

spring:
  cloud:
    gateway:
      routes:
        - id: userCmdApi-RegisterUser
          uri: http://user-cmd-api:8081/api/v1/registerUser
          predicates:
            - Path=/api/v1/registerUser

        - id: userCmdApi-UpdateUser
          uri: http://user-cmd-api:8081/api/v1/updateUser/**
          predicates:
            - Path=/api/v1/updateUser/**

        - id: userCmdApi-RemoveUser
          uri: http://user-cmd-api:8081/api/v1/removeUser/**
          predicates:
            - Path=/api/v1/removeUser/**

        - id: userQueryApi-UserLookup
          uri: http://user-query-api:8082/api/v1/userLookup/**
          predicates:
            - Path=/api/v1/userLookup/**

        - id: bankAccountCmdApi-OpenAccount
          uri: http://bankacc-cmd-api:9091/api/v1/openBankAccount
          predicates:
            - Path=/api/v1/openBankAccount

        - id: bankAccountCmdApi-DepositFunds
          uri: http://bankacc-cmd-api:9091/api/v1/depositFunds/**
          predicates:
            - Path=/api/v1/depositFunds/**

        - id: bankAccountCmdApi-WithdrawFunds
          uri: http://bankacc-cmd-api:9091/api/v1/withdrawFunds/**
          predicates:
            - Path=/api/v1/withdrawFunds/**

        - id: bankAccCmdApi-CloseAccount
          uri: http://bankacc-cmd-api:9091/api/v1/closeBankAccount/**
          predicates:
            - Path=/api/v1/closeBankAccount/**

        - id: bankAccQueryApi-UserLookup
          uri: http://bankacc-query-api:9082/api/v1/bankAccountLookup/**
          predicates:
            - Path=/api/v1/bankAccountLookup/**